
language: python
python:
  - '3.6'
services:
  - docker
install:
  - sudo service mysql stop
  - docker-compose -f db-compose.yml up -d
script:
  - docker-compose up -d
  - docker-compose run models python manage.py test
  
