version: '3'

services:
  db:
    image: mysql:5.7.23
    container_name: mysql
    ports:
    - "3306:3306"
    restart: always
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: $$3cureUS
      MYSQL_DATABASE: cs4501
      MYSQL_USER: www
      MYSQL_PASSWORD: $$3cureUS