version: '3'

services:
  models:
    build: ./models/.
    container_name: models
    network_mode: "bridge"
    external_links:
      - mysql:db
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loaddata db.json
      && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/Sothebys/wsgi.py"
    volumes:
      - ./models:/app
    ports:
      - "8001:8000"
  web:
    build: ./web/.
    container_name: web
    network_mode: "bridge"
    links:
      - exp:exp-api
    command: >
      bash -c "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/web/wsgi.py"
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
  exp:
    build: ./exp/.
    container_name: exp
    network_mode: "bridge"
    links:
      - models:models-api
    command: >
      bash -c "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/exp/wsgi.py"
    volumes:
      - ./exp:/app
    ports:
      - "8002:8000"

