version: '3'

services:
  db:
    image: mysql:5.7.23
    ports:
    - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: randilovers
      MYSQL_DATABASE: Sothebys
      MYSQL_USER: admin
      MYSQL_PASSWORD: randilovers
  web:
    build: ./web/.
    container_name: web
    links:
      - exp:exp-api
    command: >
      bash -c "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/web/wsgi.py"
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
  exp:
    build: ./exp/.
    container_name: exp
    links:
      - models:models-api
    command: >
      bash -c "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/exp/wsgi.py"
    volumes:
      - ./exp:/app
    ports:
      - "8002:8000"
  models:
    build: ./models/.
    container_name: models
    command: >
      bash -c "./wait-for-it.sh db:3306 && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loaddata db.json
      && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/Sothebys/wsgi.py"
    volumes:
      - ./models:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
