# Generated by Django 2.1 on 2019-02-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('dob', models.DateField(blank=True)),
                ('dod', models.DateField(blank=True)),
            ],
        ),
    ]
