# Generated by Django 2.1 on 2019-02-19 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_auto_20190219_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 21, 14, 8, 696550)),
        ),
    ]
