# Generated by Django 2.1 on 2019-03-10 01:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_auto_20190310_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 10, 1, 21, 29, 629226, tzinfo=utc)),
        ),
    ]
