# Generated by Django 2.1 on 2019-02-19 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0006_auto_20190219_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 21, 30, 53, 490437)),
        ),
    ]
