# Generated by Django 2.1 on 2019-03-10 02:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0006_auto_20190310_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 10, 2, 16, 58, 267025, tzinfo=utc)),
        ),
    ]
