# Generated by Django 2.1 on 2019-02-19 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0009_auto_20190219_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 21, 38, 14, 195126, tzinfo=utc)),
        ),
    ]
