# Generated by Django 2.1 on 2019-03-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0003_auto_20190310_0131'),
        ('paintings', '0010_auto_20190310_0544'),
    ]

    operations = [
    ]
