# Generated by Django 2.1 on 2019-02-20 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190206_0023'),
        ('paintings', '0011_auto_20190220_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='painting',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 20, 6, 16, 6, 186336, tzinfo=utc)),
        ),
    ]
