# Generated by Django 2.1 on 2019-02-21 00:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0012_auto_20190220_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 21, 0, 45, 28, 222179, tzinfo=utc)),
        ),
    ]
