# Generated by Django 2.1 on 2019-02-20 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0013_auto_20190220_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 20, 17, 50, 36, 520309, tzinfo=utc)),
        ),
    ]
