# Generated by Django 2.1 on 2019-02-20 23:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0015_auto_20190220_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 20, 23, 25, 43, 515701, tzinfo=utc)),
        ),
    ]
