# Generated by Django 2.1 on 2019-02-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='shipping',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.CharField(default='DEFAULT VALUE', max_length=150),
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.CharField(default='DEFAULT VALUE', max_length=150),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
