# Generated by Django 2.1 on 2019-02-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('password', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('first_name', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('last_name', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('phone', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('shipping', models.CharField(default='DEFAULT VALUE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('password', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('first_name', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('last_name', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('phone', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('description', models.CharField(default='DEFAULT VALUE', max_length=150)),
                ('logo', models.CharField(default='DEFAULT VALUE', max_length=150)),
            ],
        ),
    ]
