# Generated by Django 2.1 on 2019-03-09 01:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticator', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 9, 1, 49, 50, 81018, tzinfo=utc))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Buyer')),
            ],
        ),
    ]
