# Generated by Django 2.1 on 2019-03-10 00:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190309_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 10, 0, 56, 45, 648051, tzinfo=utc)),
        ),
    ]
