# Generated by Django 2.1 on 2019-03-10 01:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190310_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 10, 1, 29, 11, 11355, tzinfo=utc)),
        ),
    ]
