# Generated by Django 2.1 on 2019-03-10 05:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190310_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 10, 5, 44, 40, 793746, tzinfo=utc)),
        ),
    ]
