# Generated by Django 2.1 on 2019-02-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paitings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('medium', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
